sign: avoid pkey conversion on sign operation
We observe this error, specifically when trying to run with
tpm2-tss-engine:

ERROR: EVP_PKEY_fromdata_init: error:03000096:digital envelope routines::operation not supported for this keytype
40B7BEF79B7F0000:error:41800002:PKCS#11 module:ERR_CKR_error:Host memory error:p11_rsa.c:153:
40B7BEF79B7F0000:error:06880006:asn1 encoding routines:ASN1_item_sign_ctx:EVP lib:../crypto/asn1/a_sign.c:274:

The sign operation does not need the EVP pkey field as the TPM is
responsible for it.

Signed-off-by: Moritz Buhl <moritz.buhl@infineon.com>